baseurl = "https://codeinthehole.com/"
title = "Greg"
languageCode = "en-us"

PygmentsCodeFences = true

[services]
    [services.googleAnalytics]
        ID = 'G-5TB73Q80KQ'

[params]
    author = "Greg"
    description = "A software engineer working in London."

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

ignoreLogs = ['shortcode-twitter-getremote']
